#!/usr/bin/perl

use warnings;
use strict;
use 5.12.0;

my $pcapdata = 'dns.pcap.txt';

open my $PCAPDATA, '<', $pcapdata
    or die "Can't open the pcap data file!: $!";

my %results;

while ( my $line = <$PCAPDATA> ){ 
    chomp $line;

#    my ( $requestor ) = ( split( /\s+/, $line ) )[1,6];
    my ( $requestor ) = ( split( /\s+/, $line ) )[1];

    if ( $requestor =~ /10.0.10|4.2.2.2/ ){
        next;
    }

    my ( $name ) = $line =~ /(\w+?\.\w+.\w+\.\s+)/;
#    next if $name !~ /\w+\.\w+/;
    ( $requestor ) = $requestor =~ /(\d+.\d+.\d+.\d+)/;
    print "$requestor -- $name\n";
}
    
