#!/usr/bin/perl

use warnings;
use strict;
use 5.12.0;

my $pcapdata = 'dns.pcap.txt';

open my $PCAPDATA, '<', $pcapdata
    or die "Can't open the pcap data file!: $!";

my %results;

while ( my $line = <$PCAPDATA> ){ 
    chomp $line;
    my ( $requestor, $name ) = ( split( /\s+/, $line ) )[0,6];
    say $requestor;
    say $name;
}
    
