#!/usr/bin/perl

use warnings;
use strict;
use 5.12.0;

use Data::Dumper;

my $pcapdata = 'dns.pcap.txt';

open my $PCAPDATA, '<', $pcapdata
    or die "Can't open the pcap data file!: $!";

my %results;

while ( my $line = <$PCAPDATA> ){ 
    chomp $line;

    my ( $requestor ) = ( split( /\s+/, $line ) )[1];

    if ( $requestor =~ /10.0.10|4.2.2.2/ ){
        next;
    }

    my ( $name ) = $line =~ /(\w+?-?\w+?\.\w+.\w+\.\s+)/;
    
    ( $requestor ) = $requestor =~ /(\d+.\d+.\d+.\d+)/;

    $results{ $name }{ $requestor } = $requestor; 
}

for my $k ( keys %results ){
    
    print "$k\n------------\n";

    for my $v ( keys %{ $results{ $k } } ){
        print "\t$v\n";
    }
    print "\n\n";
}
#print Dumper \%results;
    
